In [ ]:
#1. What is a Python library? Why do we use Python libraries?

In [ ]:
'''
A Python library is a collection of pre-written code that helps you perform specific tasks without writing everything from scratch. It’s like a 
toolbox filled with ready-made tools for different jobs, such as data analysis, web development, automation, and machine learning.

Saves Time & Effort – Instead of writing complex code, you can use built-in functions from libraries.
Makes Coding Easier – Libraries handle difficult tasks, so you can focus on solving problems rather than writing every detail.
Better Performance – Many libraries are optimized for speed and efficiency.
Large Community Support – Popular libraries are well-maintained and regularly updated.
Covers Various Fields – There are libraries for almost everything:
Data Analysis → pandas, numpy
Machine Learning → scikit-learn, tensorflow
Web Development → flask, django
Automation → selenium, pyautogui
Data Visualization → matplotlib, seaborn'''

In [ ]:
#2. What is the difference between Numpy array and List?

In [ ]:
'''
Both NumPy arrays and Python lists store collections of data, but they have key differences:

1. Speed & Performance 🚀
NumPy arrays are faster because they use fixed types and optimized C-based operations.
Lists are slower since they store elements as objects with extra overhead.
2. Memory Efficiency 🧠
NumPy arrays take up less memory because they store elements in a continuous block of memory.
Lists use more memory since they store references to objects, which adds extra overhead.
3. Data Type Consistency 🔢
NumPy arrays require all elements to be of the same data type (e.g., all integers or all floats).
Lists can store mixed data types (e.g., integers, strings, floats in the same list).
4. Built-in Operations 🏗️
NumPy arrays support vectorized operations (e.g., array1 + array2 adds element-wise).
Lists require manual looping (for loops) for operations like addition or multiplication.
5. Functionality & Applications 📊
NumPy arrays are great for scientific computing, data analysis, and machine learning.
Lists are more general-purpose and flexible for everyday Python programming.
'''

In [ ]:
3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [1]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3, 4], 
                [5, 6, 7, 8], 
                [9, 10, 11, 12]])

# Get shape, size, and dimension
print("Shape:", arr.shape)      # (rows, columns)
print("Size:", arr.size)        # Total number of elements
print("Dimension:", arr.ndim)   # Number of dimensions


Shape: (3, 4)
Size: 12
Dimension: 2


In [ ]:
'''
4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
'''

In [2]:
# Define the array
arr = np.array([[1, 2, 3, 4], 
                [5, 6, 7, 8], 
                [9, 10, 11, 12]])

# Access the first row
first_row = arr[0]

# Print the first row
print("First row:", first_row)


First row: [1 2 3 4]


In [ ]:
'''5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
'''

In [3]:
# Define the array
arr = np.array([[1, 2, 3, 4], 
                [5, 6, 7, 8], 
                [9, 10, 11, 12]])

# Access the element at the third row and fourth column
element = arr[2, 3]  # Indexing starts from 0

# Print the element
print("Element at third row and fourth column:", element)


Element at third row and fourth column: 12


In [ ]:
'''6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''

In [4]:
# Define the array
arr = np.array([[1, 2, 3, 4], 
                [5, 6, 7, 8], 
                [9, 10, 11, 12]])

# Extract elements where either row index or column index is odd
odd_indexed_elements = arr[1::2, 1::2]  # Select rows and columns at odd indices

# Print the result
print("Odd-indexed elements:\n", odd_indexed_elements)


Odd-indexed elements:
 [[6 8]]


In [ ]:
#7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [5]:
# Generate a 3x3 matrix with random values between 0 and 1
random_matrix = np.random.rand(3, 3)

# Print the matrix
print("Random 3x3 Matrix:\n", random_matrix)


Random 3x3 Matrix:
 [[0.70406468 0.54303527 0.4765296 ]
 [0.76510061 0.92489012 0.83809896]
 [0.24254736 0.68474035 0.97979837]]


In [ ]:
#8. Describe the difference between np.random.rand and np.random.randn?

In [7]:
#np.random.rand
#Generates random numbers between 0 and 1.
print(np.random.rand(3, 3)) 


#np.random.randn()
#Generates random numbers with a mean of 0 and a standard deviation of 1.
print(np.random.randn(3, 3))


[[0.94683314 0.64655118 0.20914904]
 [0.77255433 0.9476404  0.52090268]
 [0.40041475 0.40122619 0.63023468]]
[[-0.65349279 -0.03350103  0.71682197]
 [-1.82070527  1.21749346  2.62864618]
 [ 0.57967839  0.2111095   0.15470602]]


In [ ]:
'''9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''

In [8]:
# Define the original 2D array
arr = np.array([[1, 2, 3, 4], 
                [5, 6, 7, 8], 
                [9, 10, 11, 12]])

# Increase dimension using np.newaxis
arr_expanded1 = arr[np.newaxis, :, :]  # Adds an extra dimension at the beginning

# Increase dimension using np.expand_dims()
arr_expanded2 = np.expand_dims(arr, axis=0)  # Adds an extra dimension at axis 0

# Print results
print("Original Shape:", arr.shape)
print("New Shape (using newaxis):", arr_expanded1.shape)
print("New Shape (using expand_dims):", arr_expanded2.shape)


Original Shape: (3, 4)
New Shape (using newaxis): (1, 3, 4)
New Shape (using expand_dims): (1, 3, 4)


In [ ]:
'''10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''

In [9]:
# Define the original array
arr = np.array([[1, 2, 3, 4], 
                [5, 6, 7, 8], 
                [9, 10, 11, 12]])

# Transpose the array using .T
transposed_arr = arr.T

# Alternatively, using np.transpose()
transposed_arr2 = np.transpose(arr)

# Print the results
print("Original Array:\n", arr)
print("Transposed Array (using .T):\n", transposed_arr)
print("Transposed Array (using np.transpose()):\n", transposed_arr2)


Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Transposed Array (using .T):
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
Transposed Array (using np.transpose()):
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [ ]:
'''11. Consider the following matrix:
Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Perform the following operation using Python1
1. Index wise multiplicatio.
2. Matrix multiplicatio.
3. Add both the matrics.
4. Subtract matrix B from A.
5. Divide Matrix B by A. '''

In [10]:
# Define Matrix A and Matrix B
A = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8], 
              [9, 10, 11, 12]])

B = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8], 
              [9, 10, 11, 12]])

# Element-wise multiplication (Index-wise multiplication)
index_wise_multiplication = A * B
print("Index-wise Multiplication:\n", index_wise_multiplication)

# Matrix multiplication (Dot product)
matrix_multiplication = np.dot(A, B.T)  # B.T is the transpose of B for valid multiplication
print("Matrix Multiplication:\n", matrix_multiplication)

# Add both matrices
matrix_addition = A + B
print("Matrix Addition:\n", matrix_addition)

# Subtract Matrix B from Matrix A
matrix_subtraction = A - B
print("Matrix Subtraction (A - B):\n", matrix_subtraction)

# Divide Matrix B by Matrix A
matrix_division = B / A
print("Matrix Division (B / A):\n", matrix_division)



Index-wise Multiplication:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
Matrix Multiplication:
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
Matrix Addition:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Matrix Subtraction (A - B):
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Matrix Division (B / A):
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#12.  Which function in Numpy can be used to swap the byte order of an array?

In [12]:
# Create a NumPy array with a larger integer type (int32)
arr = np.array([1, 256, 65536], dtype='int32')  # Use int32 to accommodate 65536

print("Array:", arr)
print("Byte Order:", arr.dtype)


Array: [    1   256 65536]
Byte Order: int32


In [ ]:
#13.  What is the significance of the np.linalg.inv function?

In [13]:
# Define a square matrix
A = np.array([[1, 2], 
              [3, 4]])

# Compute the inverse of the matrix
A_inv = np.linalg.inv(A)

print("Matrix A:\n", A)
print("Inverse of A:\n", A_inv)

# Verify the result by multiplying A with its inverse
identity_matrix = np.dot(A, A_inv)
print("A * A_inv (should be identity matrix):\n", identity_matrix)

Matrix A:
 [[1 2]
 [3 4]]
Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
A * A_inv (should be identity matrix):
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [ ]:
#14. What does the np.reshape function do, and how is it used?

In [15]:
'''The np.reshape() function in NumPy is used to change the shape of an array without changing its data. It allows you to modify the dimensions of the 
array (e.g., from a 1D array to a 2D array or from a 2D array to a 3D array), as long as the total number of elements remains the same.
'''

# Create a 1D array with 12 elements
arr = np.arange(12)

print("Original Array:", arr)

# Reshape the array to 2x6 (2 rows and 6 columns)
reshaped_arr_2x6 = np.reshape(arr, (2, 6))
print("\nReshaped Array (2x6):\n", reshaped_arr_2x6)

# Reshape the array to 3x4 (3 rows and 4 columns)
reshaped_arr_3x4 = np.reshape(arr, (3, 4))
print("\nReshaped Array (3x4):\n", reshaped_arr_3x4)

# Reshape the array to 4x3 (4 rows and 3 columns)
reshaped_arr_4x3 = np.reshape(arr, (4, 3))
print("\nReshaped Array (4x3):\n", reshaped_arr_4x3)

# Using -1 to automatically infer one dimension
reshaped_arr_inferred = np.reshape(arr, (3, -1))  # Automatically infers the second dimension
print("\nReshaped Array with inferred dimension (3, -1):\n", reshaped_arr_inferred)



Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped Array (2x6):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Reshaped Array (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped Array (4x3):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Reshaped Array with inferred dimension (3, -1):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
#15. What is broadcasting in Numpy?

In [16]:
'''Broadcasting in NumPy is a feature that allows NumPy to perform arithmetic operations on arrays of different shapes, by automatically expanding the 
smaller array to match the shape of the larger one. This makes operations like adding, subtracting, or multiplying arrays with different dimensions easy
and efficient.

How Broadcasting Works:
Dimension Alignment: If the arrays have different numbers of dimensions, NumPy will add "1" to the smaller array’s shape until both arrays have the same
number of dimensions.
Shape Compatibility: For broadcasting to work, the dimensions of the two arrays must either be the same or one of them should be 1. This means that if 
one array has a smaller dimension, it will be "stretched" to match the larger one.
Stretching: If one of the arrays has a dimension of size 1, NumPy will stretch it to match the other array’s size in that dimension
'''
#example
arr = np.array([[1, 2, 3], [4, 5, 6]])
result = arr + 10  # Broadcasting the scalar 10
print(result)

[[11 12 13]
 [14 15 16]]
